name: build_docker_containers

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'          # Matches v1.2.3
      - 'v[0-9]+.[0-9]+.[0-9]+-*'        # Matches v1.2.3-alpha, v1.2.3-beta.1, etc.
    branches:
      - feature/add_docker_build
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit hash, branch name, or tag to run the CI pipeline for'
        required: false
        default: 'master'
        type: string
      cadet_python_hash:
        description: 'CADET-Python git hash or branch'
        required: false
        default: 'master'
        type: string
      cadet_process_hash:
        description: 'CADET-Process git hash or branch'
        required: false
        default: 'master'
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Use the dispatch input if provided, otherwise fall back to the triggering commit
          ref: ${{ github.event.inputs.ref || github.sha }}
          fetch-depth: 0   # Ensure all commits are available (needed for arbitrary commit SHAs including non-default branches)

      - name: Get versions for Python and Process
        run: |
          git clone https://github.com/cadet/CADET-Python tmp-python
          git -C tmp-python checkout ${{ github.event.inputs.cadet_python_hash || 'master' }}
          PYTHON_VERSION=$(grep -Po '(?<=__version__ = ")[^"]+' tmp-python/cadet/__init__.py || echo "dev")

          git clone https://github.com/fau-advanced-separations/CADET-Process tmp-process
          git -C tmp-process checkout ${{ github.event.inputs.cadet_process_hash || 'master' }}
          PROCESS_VERSION=$(grep -Po '(?<=__version__ = ")[^"]+' tmp-process/CADETProcess/__init__.py || echo "dev")

          CORE_TAG=${GITHUB_REF##*/}  # Strip refs/tags/v1.2.3 → v1.2.3

          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
          echo "PROCESS_VERSION=$PROCESS_VERSION" >> $GITHUB_ENV
          echo "CORE_TAG=$CORE_TAG" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/cadet/CADET-Suite
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') && !contains(github.ref, '-') }}   # Only set 'latest' if it's a tag AND NOT a pre-release
            type=ref,event=branch
            type=raw,value=Core-${{ env.CORE_TAG }}-Python-${{ env.PYTHON_VERSION }}-Process-${{ env.PROCESS_VERSION }}

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CADET_PYTHON_HASH=${{ github.event.inputs.cadet_python_hash || 'master' }}
            CADET_PROCESS_HASH=${{ github.event.inputs.cadet_process_hash || 'master' }}
