name: CI_coverage

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'doc/ISSUE_TEMPLATE'
      - 'doc/PULL_REQUEST_TEMPLATE'
      - '.zenodo.json'
      - 'AUTHORS.md'
      - 'BUILD-LINUX.md'
      - 'BUILD-WINDOWS.md'
      - 'BUILD-OSX.md'
      - 'CITATION.bib'
      - 'CLA.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE.txt'
      - 'README.rst'
      - 'SECURITY.md'
      - 'ThirdParty-LICENSES.txt'
      - 'version.txt'
    branches:
      - master
  pull_request :
    paths-ignore:
      - 'doc/**'
      - 'doc/ISSUE_TEMPLATE'
      - 'doc/PULL_REQUEST_TEMPLATE'
      - '.zenodo.json'
      - 'AUTHORS.md'
      - 'BUILD-LINUX.md'
      - 'BUILD-WINDOWS.md'
      - 'BUILD-OSX.md'
      - 'CITATION.bib'
      - 'CLA.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE.txt'
      - 'README.rst'
      - 'SECURITY.md'
      - 'ThirdParty-LICENSES.txt'
      - 'version.txt'
    types : [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit hash, branch name, or tag to run the coverage pipeline for'
        required: false
        default: 'master'
        type: string


jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    defaults:
      run:
        shell: bash -l {0}
    env:
      BUILD_DIR: ${{ github.workspace }}/build
      INSTALL_PREFIX: ${{ github.workspace }}/install
      BUILD_TYPE: RelWithDebInfo 
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          ref: "${{ github.event.inputs.ref || github.ref }}"
      - name: Install GCC-14
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 60
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 60
          gcc --version
          g++ --version

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt -y install \
            build-essential \
            libhdf5-dev \
            liblapack-dev \
            libblas-dev \
            libtbb-dev \
            libsuperlu-dev \
            gcovr;  # for generating code coverage
      - name: Build Eigen
        run: |
          git clone https://gitlab.com/libeigen/eigen.git
          cd eigen
          git fetch origin
          git checkout --detach origin/5.0
          cmake -S . -B build \
            -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" \
            -DEIGEN_BUILD_BLAS=OFF \
            -DEIGEN_BUILD_LAPACK=OFF \
            -DBUILD_TESTING=OFF
          cmake --install build
      - name: Build and Install
        run: |
          cmake -E make_directory "${BUILD_DIR}"
          cmake -E make_directory "${INSTALL_PREFIX}"
          cd "${BUILD_DIR}"
          cmake -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" "${{ github.workspace }}" -DENABLE_TESTS=ON -DNUM_MAX_AD_DIRS=160 -DCODE_COVERAGE=ON
          make install -j$(nproc)
      - name: Check executable
        run: |
          export LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:$LD_LIBRARY_PATH
          ${INSTALL_PREFIX}/bin/cadet-cli --version || true
          ${INSTALL_PREFIX}/bin/createLWE
          ${INSTALL_PREFIX}/bin/cadet-cli LWE.h5 || true
      - name: Run CI test set I - bindings
        run: |
          ${BUILD_DIR}/test/testRunner [CI_binding] -r junit -o junit-binding.xml
      - name: Run CI test set II - sensitivities
        run: |
          ${BUILD_DIR}/test/testRunner [CI_sens1] -r junit -o junit-sens1.xml
          ${BUILD_DIR}/test/testRunner [CI_sens2] -r junit -o junit-sens2.xml
          ${BUILD_DIR}/test/testRunner [CI_sens3] -r junit -o junit-sens3.xml
          ${BUILD_DIR}/test/testRunner [CI_sens4] -r junit -o junit-sens4.xml
          ${BUILD_DIR}/test/testRunner [CI_sens5] -r junit -o junit-sens5.xml
          ${BUILD_DIR}/test/testRunner [CI_sens6] -r junit -o junit-sens6.xml
          ${BUILD_DIR}/test/testRunner [CI_sens7] -r junit -o junit-sens7.xml
          ${BUILD_DIR}/test/testRunner [CI_sens8] -r junit -o junit-sens8.xml
          ${BUILD_DIR}/test/testRunner [CI_sens9] -r junit -o junit-sens9.xml
          ${BUILD_DIR}/test/testRunner [CI_sens11] -r junit -o junit-sens11.xml
          ${BUILD_DIR}/test/testRunner [CI_sens12] -r junit -o junit-sens12.xml
          ${BUILD_DIR}/test/testRunner [CI_sens13] -r junit -o junit-sens13.xml
          ${BUILD_DIR}/test/testRunner [CI_sens14] -r junit -o junit-sens14.xml
          ${BUILD_DIR}/test/testRunner [CI_sens15] -r junit -o junit-sens15.xml
          ${BUILD_DIR}/test/testRunner [CI_sens16] -r junit -o junit-sens16.xml
          ${BUILD_DIR}/test/testRunner [CI_sens17] -r junit -o junit-sens17.xml
          ${BUILD_DIR}/test/testRunner [CI_sens18] -r junit -o junit-sens18.xml
          ${BUILD_DIR}/test/testRunner [CI_sens19] -r junit -o junit-sens19.xml
          ${BUILD_DIR}/test/testRunner [CI_sens20] -r junit -o junit-sens20.xml
          ${BUILD_DIR}/test/testRunner [CI_sens21] -r junit -o junit-sens21.xml
          ${BUILD_DIR}/test/testRunner [CI_sens22] -r junit -o junit-sens22.xml
          ${BUILD_DIR}/test/testRunner [CI_sens23] -r junit -o junit-sens23.xml
          ${BUILD_DIR}/test/testRunner [CI_sens24] -r junit -o junit-sens24.xml
      - name: Run CI test set III - crystallization
        run: |
          ${BUILD_DIR}/test/testRunner [CI_cry1] -r junit -o junit-cry1.xml
          ${BUILD_DIR}/test/testRunner [CI_cry2] -r junit -o junit-cry2.xml
          ${BUILD_DIR}/test/testRunner [CI_cry3] -r junit -o junit-cry3.xml
          ${BUILD_DIR}/test/testRunner [CI_cry4] -r junit -o junit-cry4.xml
          ${BUILD_DIR}/test/testRunner [CI_cry5] -r junit -o junit-cry5.xml
          ${BUILD_DIR}/test/testRunner [CI_cry6] -r junit -o junit-cry6.xml
          ${BUILD_DIR}/test/testRunner [CI_cry7] -r junit -o junit-cry7.xml
          ${BUILD_DIR}/test/testRunner [CI_cry8] -r junit -o junit-cry8.xml
          ${BUILD_DIR}/test/testRunner [CI_cry9] -r junit -o junit-cry9.xml
          ${BUILD_DIR}/test/testRunner [CI_cry10] -r junit -o junit-cry10.xml
          ${BUILD_DIR}/test/testRunner [CI_cry11] -r junit -o junit-cry11.xml
          ${BUILD_DIR}/test/testRunner [CI_cry12] -r junit -o junit-cry12.xml
          ${BUILD_DIR}/test/testRunner [CI_cry13] -r junit -o junit-cry13.xml
          ${BUILD_DIR}/test/testRunner [CI_cry14] -r junit -o junit-cry14.xml
          ${BUILD_DIR}/test/testRunner [CI_cry15] -r junit -o junit-cry15.xml
          ${BUILD_DIR}/test/testRunner [CI_cry16] -r junit -o junit-cry16.xml
          ${BUILD_DIR}/test/testRunner [CI_cry17] -r junit -o junit-cry17.xml
          ${BUILD_DIR}/test/testRunner [CI_cry18] -r junit -o junit-cry18.xml
          ${BUILD_DIR}/test/testRunner [CI_cry19] -r junit -o junit-cry19.xml
          ${BUILD_DIR}/test/testRunner [CI_cry20] -r junit -o junit-cry20.xml
      - name: Run CI test set IV
        run: |
          ${BUILD_DIR}/test/testRunner [CI]

      - name: Generate Coverage Report
        run: |
          gcovr \
            --root "${{ github.workspace }}" \
            --filter "${{ github.workspace }}/(src|include|build/src)" \
            --exclude-directories '.*ThirdParty.*' \
            --cobertura -o coverage.xml \
            --gcov-executable gcov-14 \
            --txt=-
      
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: cadet/CADET-Core
          files: coverage.xml
          fail_ci_if_error : true
      - name: Upload Test Results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: cadet/CADET-Core
          files: junit-*.xml

