name: "Trigger for dispatching CADET-Website"

on:
  push:
    branches:
      - 'master'
      - 'chore/developer_guide'
  workflow_dispatch:

jobs:
  dispatch_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_DOCS }}
          repository: cadet/CADET-Website
          event-type: build_docs
